Repository Sygil-Dev/sygil-webui, pull requests merged in 2022-09, with the labels that each got.

#421 [Big update] - Dynamic params, Ui rehaul, mobile fixes, and simplification of the txt2img tab
  frontend/css/styles.css
  frontend/css_and_js.py
  frontend/frontend.py
  webui.py
  webui_playground.py
Labels: enhancement, txt2img

#1049 Fixed Sidebar CSS for 4K displays
  frontend/css/streamlit.main.css
Labels: streamlit

#1158 Fix invalid invocation of find_noise_for_image
  scripts/sd_utils.py
Labels: streamlit

#1159 Gallery fixes
  scripts/home.py
  scripts/txt2img.py
Labels: streamlit

#1181 Enable negative prompts on streamlit
  scripts/sd_utils.py
Labels: streamlit

#1190 Better handling for final displays of images
  scripts/sd_utils.py
Labels: streamlit

#1196 Add .ckpt name to output .yaml files
  scripts/sd_utils.py
Labels: streamlit

#1195 Streamlit txt2img page settings now follow defaults
  scripts/txt2img.py
Labels: streamlit

#1281 better library browser
  frontend/css/streamlit.main.css
  scripts/sd_concept_library.py
Labels: streamlit

#1262 Initial overhaul of documentation
  README.md
  configs/webui/webui_streamlit.yaml
  docs/3.cli.md
  docs/3.docker-guide.md
  docs/4.streamlit-interface.md
  docs/5.gradio-interface.md
  docs/5.upscalers.md
  docs/6.image_enhancers.md
  docs/7.concepts-library.md
  docs/8.custom-models.md
  images/gradio/gradio-i2i.png
  images/gradio/gradio-t2i.png
  images/gradio/gradio-upscale.png
  images/sd-wui_logo.png
  images/streamlit/streamlit-concepts.png
  images/streamlit/streamlit-i2i.png
  images/streamlit/streamlit-t2i.png
  images/streamlit/streamlit-t2v.png
Labels: documentation
